# Provenance

## Formal source

The counterexample underlying this manuscript comes from the machine-checked Lean 4 proof archived in:

- Repository: `tadamcz/koethe`
- Commit: `b0527558797325e98a8e57f2197e527210290dc4`
- Proof file: `Koethe/Resolutions/Koethe.lean`
- Compared theorem: `Koethe.KotherConjecture.variants.general_matrix.disproof`

Permanent links:

- https://github.com/tadamcz/koethe/tree/b0527558797325e98a8e57f2197e527210290dc4
- https://github.com/tadamcz/koethe/blob/b0527558797325e98a8e57f2197e527210290dc4/Koethe/Resolutions/Koethe.lean

According to the source repository, the Lean proof was generated by a pre-release GPT-6 Astra model (OpenAI) in an Epoch AI LeanOpenProblems evaluation. The packaged formal source was maintained by Tom Adamczewski. The source repository reports independent replay of the Lean proof through Comparator and NanoDa.

## Later simplification used here

The present manuscript also incorporates two specific simplifications from:

Tom Adamczewski, Bernhard Böhmler, and René Marczinzik,
*A counterexample to Köthe's conjecture and a question of Rowen*,
arXiv:2609.07996v1 [math.RA], 7 September 2026,
https://arxiv.org/abs/2609.07996.

The two ingredients used are:

- the minimum-rank argument of Lemma 4.6, which replaces an iterative rank-lowering construction by a one-step contradiction from a compatible word of minimal rank;
- the passage to the two-generated nil algebra generated by the final elements `b` and `c`, as in Theorem 1.1.

Both uses are cited in `paper.tex`.

## Relationship of this manuscript to the sources

The mathematical construction in `paper.tex` is not an independent discovery. It is a human-readable reconstruction and simplification of the formal counterexample, combined with the two simplifications above from Adamczewski--Böhmler--Marczinzik.

Other presentation choices in the manuscript include:

- the common-zero argument is presented through a Segre--Veronese embedding and the projective dimension theorem;
- the finite linearization of a noncommutative polynomial is written explicitly and uniformly in the ambient algebra;
- only the pencils arising from the noncommutative polynomials needed for nilness are enumerated;
- the periodic construction leaves never-prescribed positions free until the end and then fills them by a fixed nonzero vector;
- nonnilpotence of the final matrix is shown by an explicit eigenvector over `k(t)`;
- the final two nil left ideals are constructed directly, so the conclusion does not require invoking Krempa's equivalence theorem.

The formal source uses an algebraic closure of `F_2`; the arXiv paper obtains a result over arbitrary countable fields. To minimize auxiliary generality, the present manuscript fixes the countable algebraically closed field `k = \overline{\mathbb Q}`.

## Verification status

The formal theorem is machine checked in the source repository. The prose proof here has been repeatedly audited for the projective dimension count, finite linearization, Cauchy--Binet degree estimate, minimum-rank contradiction over `k(s)`, periodic construction, weighted-shift composition order, nilness argument, passage to the two-generated algebra, companion-matrix eigenvector calculation, and final left-ideal construction.

Machine checking of the original Lean theorem does not by itself constitute machine checking of this reorganized prose proof. Independent mathematical review of the manuscript remains valuable.
