# A Counterexample to Köthe's Conjecture

[![Build manuscript](https://github.com/JoseBrox/Kothe-conjecture-counterexample/actions/workflows/latex.yml/badge.svg)](https://github.com/JoseBrox/Kothe-conjecture-counterexample/actions/workflows/latex.yml)

This repository contains a human-readable proof of a counterexample to Köthe's conjecture.

The main result proved in the manuscript is:

> There exists a two-generated nil nonunital \(\overline{\mathbb Q}\)-algebra \(N=k\langle b,c\rangle_+\) such that
> \[
> \begin{pmatrix}b^2+c&bc\\ b&c\end{pmatrix}\in M_2(N)
> \]
> is not nilpotent. Consequently, there exists a unital ring containing two nil left ideals whose sum is not nil.

## Manuscript

- [LaTeX source](paper.tex)
- [Compiled PDF](https://github.com/JoseBrox/Kothe-conjecture-counterexample/blob/generated/paper.pdf) (generated automatically from `main`)

The LaTeX source is the source of truth. GitHub Actions independently rebuilds the PDF after each push to `main` and publishes the result on the `generated` branch.

## Provenance and attribution

The construction is derived from the machine-checked Lean 4 counterexample generated by a pre-release GPT-6 Astra model in an Epoch AI LeanOpenProblems evaluation and archived in [`tadamcz/koethe`](https://github.com/tadamcz/koethe). It is **not an independent discovery** of the counterexample.

The exact formal proof source used for the reconstruction is commit [`b0527558797325e98a8e57f2197e527210290dc4`](https://github.com/tadamcz/koethe/tree/b0527558797325e98a8e57f2197e527210290dc4), in particular [`Koethe/Resolutions/Koethe.lean`](https://github.com/tadamcz/koethe/blob/b0527558797325e98a8e57f2197e527210290dc4/Koethe/Resolutions/Koethe.lean).

The current hybrid proof also uses two simplifications from Adamczewski, Böhmler, and Marczinzik, *A counterexample to Köthe's conjecture and a question of Rowen*, [arXiv:2609.07996v1](https://arxiv.org/abs/2609.07996): the minimum-rank argument of Lemma 4.6 and the reduction to a two-generated nil algebra appearing in Theorem 1.1. The manuscript cites both sources explicitly.

See [PROVENANCE.md](PROVENANCE.md) for the exact relationship among the formal proof, the arXiv simplification, and this manuscript.

## Build

A TeX Live installation with `latexmk` is sufficient:

```bash
make
```

or directly:

```bash
latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode paper.tex
```

## Review status

The original Lean theorem is machine checked. The human-readable reconstruction in this repository has been repeatedly audited for internal consistency, including the projective dimension count, finite linearization, Cauchy--Binet degree estimate, minimum-rank argument, periodic construction, weighted-shift composition order, two-generated endpoint, companion-matrix eigenvector calculation, and final left-ideal construction. It has not yet undergone independent journal peer review.

Mathematical corrections are welcome through GitHub issues; please identify the relevant section, theorem, lemma, or displayed equation.

## License

This repository is distributed under the [Apache License 2.0](LICENSE). Attribution and source notices are recorded in [NOTICE](NOTICE) and [PROVENANCE.md](PROVENANCE.md).
